/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "AlarmActuatorDriver.h"
#include "AlarmMonitor.h"
#include "mainAlgo.h"
#include "PressureSensorDriver.h"
#include "driver/driver.h"

void setup()
{
	GPIO_INITIALIZATION();
	PS_init();
	AAD_init();
	AAD_state = STATE(AAD_waiting);
	AM_state = STATE(AM_alarmOFF);
	MA_state = STATE(MA_HighPressureDetect);
	PS_state = STATE(PS_reading);
}

int main()
{
	setup();
	while(1)
	{
		PS_state();
		MA_state();
		AM_state();
		AAD_state();
	}
}
