/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 		0x40010800
#define GPIOA_CRL 		*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH 		*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_IDR 		*(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_ODR 		*(volatile uint32_t *)(GPIOA_BASE + 0x0C)

#define GPIOB_BASE 		0x40010C00
#define GPIOB_CRL 		*(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH 		*(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_IDR 		*(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOB_ODR 		*(volatile uint32_t *)(GPIOB_BASE + 0x0C)

#define RCC_BASE		0x40021000
#define RCC_APB2ENR 	*(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR	 	*(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR	 		*(volatile uint32_t *)(RCC_BASE + 0x00)

#define EXTI_BASE		0x40010400
#define EXTI_RSTR		*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_IMR		*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_PR			*(volatile uint32_t *)(EXTI_BASE + 0x14)

#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)

#define NVIC_BASE		0xE000E000
#define NVIC_ISER0		*(volatile uint32_t *)(NVIC_BASE + 0x100)


void clock_init(void)
{
	// IOPAEN enables GPIOA
	RCC_APB2ENR |= 1<<2;

	// IOPAEN enables GPIOB
	RCC_APB2ENR |= 1<<3;
}

void GPIO_init(void)
{
	GPIOA_CRL = 0;
	GPIOA_CRH = 0;

	GPIOB_CRL = 0;
	GPIOB_CRH = 0;

	// PORTA pin1 input floating
	GPIOA_CRL |= (1<<6);

	// PORTA pin12 input floating
	GPIOA_CRH |= (1<<18);

	// PORTB pin1 output push-pull 10MHz
	GPIOB_CRL |= (1<<4);

	// PORTB pin13 output push-pull 10MHz
	GPIOB_CRH |= (1<<16);
}

void my_wait(unsigned int x);

int main(void)
{

	clock_init();
	GPIO_init();

	while(1)
	{
		if(((GPIOA_IDR & (1<<1))>>1) == 0)
		{
			GPIOB_ODR ^= (1<<1);
			while(((GPIOA_IDR & (1<<1))>>1) == 0);
		};

		if(((GPIOA_IDR & (1<<12))>>12) == 1)
		{
			GPIOB_ODR ^= (1<<12);
		};
		my_wait(1000);
	}
}

void my_wait(unsigned int x)
{
	int i, j;
	for(i = 0; i < x; i++)
		for(j = 0; j < 255; j++);
}

