/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 		0x40010800
#define GPIOA_CRL 		*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH 		*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR 		*(volatile uint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE		0x40021000
#define RCC_APB2ENR 	*(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR	 	*(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR	 		*(volatile uint32_t *)(RCC_BASE + 0x00)

#define EXTI_BASE		0x40010400
#define EXTI_RSTR		*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_IMR		*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_PR			*(volatile uint32_t *)(EXTI_BASE + 0x14)

#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)

#define NVIC_BASE		0xE000E000
#define NVIC_ISER0		*(volatile uint32_t *)(NVIC_BASE + 0x100)


void clock_init(void)
{
	RCC_APB2ENR |= 1<<2; 		// IOPAEN enables GPIOA

	//Enable clock for AFIO peripheral
	RCC_APB2ENR |= (1<<0);
}

void GPIO_init(void)
{
	//pin13 portA output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//pin0 portA floating input
	GPIOA_CRL &= 0xFFFFFFF0;
	GPIOA_CRL |= 0x000000004;
}

int main(void)
{

	clock_init();
	GPIO_init();

	//Rising edge for input line 0
	EXTI_RSTR |= (1<<0);

	//Remove mask line 0 in interrupt mask register
	EXTI_IMR |= (1<<0);

	//configure EXTI0 for pin A0
	AFIO_EXTICR1 = (0b0000<<0);

	//enable NVIC interrupt number 6 for EXTI0
	NVIC_ISER0 |= (1<<6);

	while(1)
	{
	}
}

void EXTI0_IRQHandler(void)
{
	//reset pending request for line 0 in EXTI_PR
	EXTI_PR |= (1<<0);

	//EXTI0 PORTA pin0 rising edge
	//toggle led pin 13 PORTA
	GPIOA_ODR ^= 1<<13 ;
}
